### ISSUE TITLE
rigid modal displacement issue

### ISSUE THREAD

**Issue by xiaomaiAI** [pyansys/pymapdl-reader#71] opened 2021-09-26 08:48 UTC
Hi，
I've put the displacements solve from ANSYS and the displacements get from pymapdl-reader into comparation，I found the rigid modal displacements are different，is that not get from result file directly？why？ THANKS.

**Comment by pmaroneh** [comment] 2021-09-27 09:03
Hi,
You should indeed obtain similar results. Could you please share a small model and script that reproduces the issue so that I can look into it?
Thanks

**Comment by xiaomaiAI** [comment] 2021-09-27 10:12
[file.zip](https://github.com/pyansys/pymapdl-reader/files/7235389/file.zip)

**Comment by pmaroneh** [comment] 2021-09-28 14:36
Thanks for sending the .cdb input file and the result file. The .cdb does not define the type of analysis so I will not be able to rerun the model. I can however work from the .rst file directly. But I would need more information to be able to reproduce the problem: which postprocessing commands have you used, both in Ansys and in PyAnsys? Could you also share a screenshot of the difference that you have obtained?

**Comment by RGPATCHI** [comment] 2021-09-28 17:05
Hi @xiaomaiAI  

I solved the uploaded cdb file (Modal analysis) and used the rst file generated to compare the results between MAPDL and PyMAPDL. They look same. Please let me know if I am missing something. 

I pasted the comparison for 1st mode for reference. I have also checked for other modes as well.

MAPDL - 1st Mode - Total Deformation Plot
![image](https://user-images.githubusercontent.com/84843983/135131188-f471fdda-536d-480d-8cd6-10ab2b692711.png)

PyMAPDL - 1st Mode - Total Deformation Plot
![image](https://user-images.githubusercontent.com/84843983/135131293-5975da43-b311-4a39-b0e7-beb77620879b.png)

In addition, I have also checked using the uploaded rst (instead of the rst from the solved model using the cdb file), I see that this uploaded rst (i.e. interfrf.rst) file has different displacement results as compared to the rst (from solving cdb file).  

I believe, the rigid body mode displacements are sensitive to whether the solution is done via SMP (Shared Memory Parallel) or DMP (Distributed Memory Parallel), as well as number of cores used. 

I would suggest to use same setting SMP/DMP and number of cores in both MAPDL and PyMAPDL to do an apple to apple comparison. 

Hope this helps.

**Comment by xiaomaiAI** [comment] 2021-10-08 02:03
Thanks. @RGPATCHI  and @pmaroneh 
I have checked the numbers of the rigid body mode displacements between MAPDL and PyMAPDL,  I found they have different displacement results, not just the plot, maybe very close. And I'll test as your suggestions. THANKS.

**Comment by jgd10** [comment] 2022-01-26 17:29
It looks like this has been resolved so I'm going to close the issue. If there are still things to cover we can reopen it!

**Closed by jgd10** 2022-01-26 17:29 UTC
