### ISSUE TITLE
Error while running self._resultheader['ptrGEO']

### ISSUE THREAD

**Issue by NDfp** [pyansys/pymapdl-reader#51] opened 2021-06-29 15:27 UTC
Hello,
I am trying to import some data from an .rst file.
Unfortunately, when running:
`result = Result('file.rst', read_mesh=False)`
I get the following error:
```
Traceback (most recent call last):
[...]
  File "C:\Users\xxx\.conda\envs\fattool_dev\lib\site-packages\ansys\mapdl\reader\rst.py", line 120, in __init__
    table = self.read_record(self._resultheader['ptrGEO'])
  File "C:\Users\xxx\.conda\envs\fattool_dev\lib\site-packages\ansys\mapdl\reader\common.py", line 107, in read_record
    record = self._cfile.read_record(pointer, return_bufsize)
  File "ansys\mapdl\reader\cython\_binary_reader.pyx", line 245, in ansys.mapdl.reader._binary_reader.AnsysFile.read_record
  File "ansys\mapdl\reader\cython\_binary_reader.pyx", line 364, in ansys.mapdl.reader._binary_reader.wrap_array
  File "ansys\mapdl\reader\cython\_binary_reader.pyx", line 155, in ansys.mapdl.reader._binary_reader.ArrayWrapper.__array__
ValueError: negative dimensions are not allowed
```
Do you have any suggestions concerning the possible cause?
Might the problem be related to the .rst being generated with an older Ansys version (19.2)?

Thank you
Francesco

**Comment by akaszynski** [comment] 2021-06-29 16:13
Quite likely.  Can you upload the file here or if you're not comfortable with that, to my business email at alexander.kaszynski@ansys.com

**Comment by akaszynski** [comment] 2021-07-01 05:00
I'm unable to reproduce the error using the latest `ansys-mapdl-reader` on either Linux or Windows Python 3.8 with:
```py
from ansys.mapdl import reader

rst = reader.read_binary('file.rst')

rst_ = reader.rst.Result('file.rst', read_mesh=True)
```

Could you please verify this error occurs on the file you sent to my work email?

**Comment by NDfp** [comment] 2021-07-05 08:17
I have found out that the cause of the error is that the file is read-only. When removing the read-only, the import works correctly.
I checked in common.py and the file is opened as read. Do you know what could cause the error?

**Comment by akaszynski** [comment] 2021-07-05 19:10
> I checked in common.py and the file is opened as read ('rb')

`'rb'` is just read binary, so that shouldn't be an issue, but there's another spot in the file where I open it as a `fstream`, which is read/write.

There was a feature request a while ago to overwrite results in the result file that resulted in a significant refactor of the code base.  I could allow an option to open in read/read write, but that's a non-trivial PR.

Is it possible just to disable the read-only flag?

**Comment by jgd10** [comment] 2022-01-26 17:02
@NDfp @akaszynski This issue seems to have stalled. Do we need to implement a new issue to cover the non-trivial work that akaszynski suggests or is disabling the read-only flag sufficient to close this issue?

**Comment by jgd10** [comment] 2022-01-26 17:33
It's been long enough since the last comment that I think it is safe to close this issue for now, unless anything else comes up and we can reopen it.

**Closed by jgd10** 2022-01-26 17:33 UTC
