### ISSUE TITLE
plot principle stress in combination with a MASS21-element

### ISSUE THREAD

**Issue by REM2021** [pyansys/PyMAPDL-reader#42] opened 2021-05-31 14:48 UTC
Dear Mr. Akazynski, 

We work with cruciform joints and have a problem regarding the principle stress in combination with a MASS21-element for the CERIG-command.

[issueplotstress.pdf](https://github.com/pyansys/PyMAPDL/files/6570969/issueplotstress.pdf)

**Comment by akaszynski** [comment] 2021-06-17 16:46
Seems there's two issues.  The first is the plotting issue which will be fixed in #34.  The second is a MAPDL issue, which I'll have to create a separate issue for.  Will close this issue and create a second.

Release for `pymapdl-reader` with this fix will be out today.

**Comment by akaszynski** [comment] 2021-06-17 16:51
Can't reproduce large `V_b` issue on 2021R1 or 2021R2.  I'm using the newer gRPC interface that might be more stable.  CORBA support isn't great...

**Comment by akaszynski** [comment] 2021-06-17 17:24
Bugfix added in ``ansys-mapdl-reader==0.51.0``.  Release should be out in an hour.

**Closed by akaszynski** 2021-06-17 17:24 UTC
